package view;

import controller.Controller;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author kenzo
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public Front() {
        initComponents();
        control = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        L00 = new javax.swing.JLabel();
        L01 = new javax.swing.JLabel();
        L02 = new javax.swing.JLabel();
        L03 = new javax.swing.JLabel();
        L04 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L22 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L21 = new javax.swing.JLabel();
        L30 = new javax.swing.JLabel();
        L23 = new javax.swing.JLabel();
        L31 = new javax.swing.JLabel();
        L24 = new javax.swing.JLabel();
        L32 = new javax.swing.JLabel();
        L33 = new javax.swing.JLabel();
        L34 = new javax.swing.JLabel();
        L41 = new javax.swing.JLabel();
        L42 = new javax.swing.JLabel();
        L40 = new javax.swing.JLabel();
        L43 = new javax.swing.JLabel();
        L44 = new javax.swing.JLabel();
        L51 = new javax.swing.JLabel();
        L50 = new javax.swing.JLabel();
        L52 = new javax.swing.JLabel();
        L53 = new javax.swing.JLabel();
        L54 = new javax.swing.JLabel();
        submit_txtfield = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        L00.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L01.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L02.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L03.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L04.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L04.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L31.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L33.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L34.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L41.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L42.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L42.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L40.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L43.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L43.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L44.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L44.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L51.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L51.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L50.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L50.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L52.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L53.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L53.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        L54.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        L54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        L54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        submit_txtfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submit_txtfieldKeyPressed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(L20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(L10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(L41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(L42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(L31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(L32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(L51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(L52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(L00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(submit_txtfield))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(L03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(L04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(submit)))
                        .addContainerGap(8, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L00, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L01, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L02, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L03, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L04, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if(submit_txtfield.getText().length() != 5){
            while(submit_txtfield.getText().length() != 5){
                JOptionPane.showMessageDialog(rootPane, "A PALAVRA NAO POSSUI 5 LETRAS");
                submit_txtfield.setText("");
                break;
            }
        }
        else{
            cnt++;
            if(cnt == 1){
                answer = control.NewWord().toUpperCase();
            }
            control.Search(cnt, answer);
            submit_txtfield.setText("");
        }
    }//GEN-LAST:event_submitActionPerformed

    private void submit_txtfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submit_txtfieldKeyPressed
        char key = evt.getKeyChar();
        if(key >= 'a' && evt.getKeyChar() <= 'z'){
            
        }
    }//GEN-LAST:event_submit_txtfieldKeyPressed
    
    private int cnt = 0;
    private String answer;
    public JButton getSubmit() {
        return submit;
    }

    public JTextField getSubmit_txtfield() {
        return submit_txtfield;
    }

    public int getCnt() {
        return cnt;
    }

    public void setCnt(int cnt) {
        this.cnt = cnt;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public Controller getControl() {
        return control;
    }

    public void setControl(Controller control) {
        this.control = control;
    }

    public JLabel getL00() {
        return L00;
    }

    public void setL00(JLabel L00) {
        this.L00 = L00;
    }

    public JLabel getL01() {
        return L01;
    }

    public void setL01(JLabel L01) {
        this.L01 = L01;
    }

    public JLabel getL02() {
        return L02;
    }

    public void setL02(JLabel L02) {
        this.L02 = L02;
    }

    public JLabel getL03() {
        return L03;
    }

    public void setL03(JLabel L03) {
        this.L03 = L03;
    }

    public JLabel getL04() {
        return L04;
    }

    public void setL04(JLabel L04) {
        this.L04 = L04;
    }

    public JLabel getL10() {
        return L10;
    }

    public void setL10(JLabel L10) {
        this.L10 = L10;
    }

    public JLabel getL11() {
        return L11;
    }

    public void setL11(JLabel L11) {
        this.L11 = L11;
    }

    public JLabel getL12() {
        return L12;
    }

    public void setL12(JLabel L12) {
        this.L12 = L12;
    }

    public JLabel getL13() {
        return L13;
    }

    public void setL13(JLabel L13) {
        this.L13 = L13;
    }

    public JLabel getL14() {
        return L14;
    }

    public void setL14(JLabel L14) {
        this.L14 = L14;
    }

    public JLabel getL20() {
        return L20;
    }

    public void setL20(JLabel L20) {
        this.L20 = L20;
    }

    public JLabel getL21() {
        return L21;
    }

    public void setL21(JLabel L21) {
        this.L21 = L21;
    }

    public JLabel getL22() {
        return L22;
    }

    public void setL22(JLabel L22) {
        this.L22 = L22;
    }

    public JLabel getL23() {
        return L23;
    }

    public void setL23(JLabel L23) {
        this.L23 = L23;
    }

    public JLabel getL24() {
        return L24;
    }

    public void setL24(JLabel L24) {
        this.L24 = L24;
    }

    public JLabel getL30() {
        return L30;
    }

    public void setL30(JLabel L30) {
        this.L30 = L30;
    }

    public JLabel getL31() {
        return L31;
    }

    public void setL31(JLabel L31) {
        this.L31 = L31;
    }

    public JLabel getL32() {
        return L32;
    }

    public void setL32(JLabel L32) {
        this.L32 = L32;
    }

    public JLabel getL33() {
        return L33;
    }

    public void setL33(JLabel L33) {
        this.L33 = L33;
    }

    public JLabel getL34() {
        return L34;
    }

    public void setL34(JLabel L34) {
        this.L34 = L34;
    }

    public JLabel getL40() {
        return L40;
    }

    public void setL40(JLabel L40) {
        this.L40 = L40;
    }

    public JLabel getL41() {
        return L41;
    }

    public void setL41(JLabel L41) {
        this.L41 = L41;
    }

    public JLabel getL42() {
        return L42;
    }

    public void setL42(JLabel L42) {
        this.L42 = L42;
    }

    public JLabel getL43() {
        return L43;
    }

    public void setL43(JLabel L43) {
        this.L43 = L43;
    }

    public JLabel getL44() {
        return L44;
    }

    public void setL44(JLabel L44) {
        this.L44 = L44;
    }

    public JLabel getL50() {
        return L50;
    }

    public void setL50(JLabel L50) {
        this.L50 = L50;
    }

    public JLabel getL51() {
        return L51;
    }

    public void setL51(JLabel L51) {
        this.L51 = L51;
    }

    public JLabel getL52() {
        return L52;
    }

    public void setL52(JLabel L52) {
        this.L52 = L52;
    }

    public JLabel getL53() {
        return L53;
    }

    public void setL53(JLabel L53) {
        this.L53 = L53;
    }

    public JLabel getL54() {
        return L54;
    }

    public void setL54(JLabel L54) {
        this.L54 = L54;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    
    
    private Controller control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L00;
    private javax.swing.JLabel L01;
    private javax.swing.JLabel L02;
    private javax.swing.JLabel L03;
    private javax.swing.JLabel L04;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L22;
    private javax.swing.JLabel L23;
    private javax.swing.JLabel L24;
    private javax.swing.JLabel L30;
    private javax.swing.JLabel L31;
    private javax.swing.JLabel L32;
    private javax.swing.JLabel L33;
    private javax.swing.JLabel L34;
    private javax.swing.JLabel L40;
    private javax.swing.JLabel L41;
    private javax.swing.JLabel L42;
    private javax.swing.JLabel L43;
    private javax.swing.JLabel L44;
    private javax.swing.JLabel L50;
    private javax.swing.JLabel L51;
    private javax.swing.JLabel L52;
    private javax.swing.JLabel L53;
    private javax.swing.JLabel L54;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    private javax.swing.JTextField submit_txtfield;
    // End of variables declaration//GEN-END:variables
}
